### ISSUE TITLE
Edit the order of the gates

### ISSUE THREAD

**Issue by yixjia** [microsoft/AirSim-Drone-Racing-Lab#4]
Hello,

My teammates and I are trying to implement our planning algorithm and we're wondering if there is a way for us to edit the order that we can pass through the gates?

Thank you!

**Comment by yixjia** [comment]
Nvm, just found out we can order the gates easily by ourselves.

**Comment by krsandeep98** [comment]
@LucasYXJ can you give some details on how to go about changing the order of the gates? Also, have you experimented with altering the position of the gates in the environment? I only have access to the binary file in the `ADRL/Binaries/Linux` folder and am not sure how to change that. Should we use the `simSetObjectPose` api?
@madratman @saihv @sytelus  Tagging others as well, let me know if you need more details to answer.

**Comment by yixjia** [comment]
Hi, I actually alternated the order that the drone passes through the gates instead of the order of the gates. I've not tried to alter positions of the gates in the environment.

**Comment by krsandeep98** [comment]
Just wanted to clarify, do you mean that you passed the gates information in a different manner (order) to the drone and let the drone cross them in that order?

**Comment by yixjia** [comment]
Yes.
