### ISSUE TITLE
where can I enable OpenGL of the airsim

### ISSUE THREAD

**Issue by lanyusea** [microsoft/AirSim-Drone-Racing-Lab#6]
Hi, I'm trying to run the ADRL in a remote Linux Server.

According to https://github.com/microsoft/AirSim/issues/2139 I have to use the virtualGL and TurtleVNC since the [Vulkan will not work over X11 forwarding](https://www.reddit.com/r/vulkan/comments/ee26p4/cant_get_vulkan_to_work_on_a_new_user_through/)

After configuration, I start the ADRL by command 
`DISPLAY=:8 vglrun -d :7.0 ./ADRL.sh -opengl4`

The program can start but with a pop-up error:
![image](https://user-images.githubusercontent.com/2766729/110234289-9fd62200-7f64-11eb-9615-937dec28d2b3.png)

      Trying to force OpenGL RHI but the project does not have it in TargetedRHIs list.

All searching asks me to modify the engine setting to enable `TargetedRHIs=GLSL_430`:
https://answers.unrealengine.com/questions/920624/view.html
https://answers.unrealengine.com/questions/936174/view.html

but I cannot find a `BaseEngine.ini` in the folder ADRL I wgeted.

Is there any way to force ADRL to run with OpenGL?

**Comment by saihv** [comment]
@lanyusea Unfortunately, Unreal Engine has deprecated OpenGL and it is no longer officially supported in the releases. 

Do you really need forwarding from your remote server? Or are you just trying to run AirSim headless on the server?

**Comment by lanyusea** [comment]
@saihv due to some technical limits I had to do the forward.

but I finally solved it by moving to the server room and plug a monitor. It feels so cold but I can close this issue now :p
